name: Build PDF Scanner Installer

on:
  push:
    branches:
      - main  # Cambiá si usás otra rama
    paths: # Solo ejecuta el workflow si hay cambios en estos paths:
      - '**/*.py'         # Si tus archivos Python están en la raíz o subcarpetas
      - 'resourses/**'  # Si tus recursos están en una carpeta llamada 'resources'
      - 'translations/**'  # Si tus recursos están en una carpeta llamada 'resources'
      - '*.spec'         # Si usás un archivo .spec de PyInstaller
      - '*.iss'

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Descarga tu código desde GitHub
      - name: Checkout repo
        uses: actions/checkout@v4

      # Instala la versión de Python necesaria
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.4'  # O la que uses localmente

      # Instala las dependencias de tu programa
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller pymupdf PyPDF2 PyQt5 requests docx2pdf pdf2docx

      - name: Actualizar __version__ automáticamente
        shell: pwsh
        run: |
          $newVersion = "v1.0.${{ github.run_number }}"
          $replacementString = "__version__ = `"$newVersion`""
          (Get-Content logic/AutoUpdater.py) -replace '__version__ = ".*"', $replacementString | Set-Content logic/AutoUpdater.py

          $pattern = 'AppVersion=.*'
          $replacement = "AppVersion=$newVersion"
          (Get-Content script_instalacion.iss) -replace $pattern, $replacement | Set-Content script_instalacion.iss

      # Ejecuta PyInstaller con tu archivo .spec
      - name: Run PyInstaller
        run: |
          pyinstaller Scanner_PDF.spec

      # Descarga e instala Inno Setup de forma silenciosa
      - name: Install Inno Setup via Chocolatey
        run: choco install innosetup --yes

      # Compila el instalador usando tu archivo .iss personalizado
      - name: Build installer with Inno Setup
        run: |
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "script_instalacion.iss"

      - name: Create GitHub Release and Upload Installer
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "PDF Scanner v1.0.${{ github.run_number }} - Build del ${{ github.event.head_commit.timestamp }}"
          body: |
            Instalador automático generado con GitHub Actions.
            - Compilación basada en la rama `main`.
            - Incluye el instalador `.exe` empaquetado con Inno Setup.
          draft: false
          prerelease: false
          files: Output/*.exe # Asegúrate de que esta sea la ruta correcta de tu instalador
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
